# ~/.dotfiles/zsh/api-keys.zsh — Secure API Key Management
#
# Prompts for API keys on first run and stores them in ~/.dotfiles/.env.api-keys
# This file is gitignored to prevent committing secrets to the repo.

API_KEYS_FILE="$HOME/.dotfiles/.env.api-keys"

# Create the file if it doesn't exist
if [[ ! -f "$API_KEYS_FILE" ]]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  API Key Setup"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Enter your API keys below (press Enter to skip any):"
    echo "Keys will be securely stored in: $API_KEYS_FILE"
    echo ""

    # Array to store key-value pairs
    typeset -A api_keys

    # OpenAI
    echo -n "OpenAI API Key: "
    read -r openai_key
    [[ -n "$openai_key" ]] && api_keys[OPENAI_API_KEY]="$openai_key"

    # Anthropic
    echo -n "Anthropic API Key: "
    read -r anthropic_key
    [[ -n "$anthropic_key" ]] && api_keys[ANTHROPIC_API_KEY]="$anthropic_key"

    # Gemini (Google AI Studio)
    echo -n "Gemini API Key: "
    read -r gemini_key
    [[ -n "$gemini_key" ]] && api_keys[GEMINI_API_KEY]="$gemini_key"

    # Mistral
    echo -n "Mistral API Key: "
    read -r mistral_key
    [[ -n "$mistral_key" ]] && api_keys[MISTRAL_API_KEY]="$mistral_key"

    # Write to file with restrictive permissions
    touch "$API_KEYS_FILE"
    chmod 600 "$API_KEYS_FILE"  # Only owner can read/write

    {
        echo "# API Keys — Auto-generated by zsh/api-keys.zsh"
        echo "# This file is gitignored. To regenerate, delete this file and restart your shell."
        echo ""
        for key val in ${(kv)api_keys}; do
            echo "export $key=\"$val\""
        done
    } > "$API_KEYS_FILE"

    echo ""
    echo "✓ API keys saved to: $API_KEYS_FILE"
    echo "  (File permissions: 600 - only you can read it)"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
fi

# Source the API keys file
if [[ -f "$API_KEYS_FILE" ]]; then
    source "$API_KEYS_FILE"
fi
